// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHJMTDWkPImmHn3TOMAF6bTCMCmQ1QKng',
    appId: '1:981955885577:web:8ddfa46609fe3fd7c9d6d8',
    messagingSenderId: '981955885577',
    projectId: 'eight-gps-project',
    authDomain: 'eight-gps-project.firebaseapp.com',
    storageBucket: 'eight-gps-project.firebasestorage.app',
    measurementId: 'G-8YL4RWFYJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFVfae2aLIUk0Y1sFywI4BdBlkhb3yVB8',
    appId: '1:981955885577:android:3168b6418184e95dc9d6d8',
    messagingSenderId: '981955885577',
    projectId: 'eight-gps-project',
    storageBucket: 'eight-gps-project.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXASp2KWmTfkkKybZRxBJStj5jXXKphaM',
    appId: '1:981955885577:ios:626f7e8fda4c4d96c9d6d8',
    messagingSenderId: '981955885577',
    projectId: 'eight-gps-project',
    storageBucket: 'eight-gps-project.firebasestorage.app',
    iosBundleId: 'com.example.webApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXASp2KWmTfkkKybZRxBJStj5jXXKphaM',
    appId: '1:981955885577:ios:626f7e8fda4c4d96c9d6d8',
    messagingSenderId: '981955885577',
    projectId: 'eight-gps-project',
    storageBucket: 'eight-gps-project.firebasestorage.app',
    iosBundleId: 'com.example.webApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHJMTDWkPImmHn3TOMAF6bTCMCmQ1QKng',
    appId: '1:981955885577:web:e8ffec4649979e53c9d6d8',
    messagingSenderId: '981955885577',
    projectId: 'eight-gps-project',
    authDomain: 'eight-gps-project.firebaseapp.com',
    storageBucket: 'eight-gps-project.firebasestorage.app',
    measurementId: 'G-0GZVTGJK8P',
  );
}
