// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHJMTDWkPImmHn3TOMAF6bTCMCmQ1QKng',
    appId: '1:981955885577:web:8ddfa46609fe3fd7c9d6d8',
    messagingSenderId: '981955885577',
    projectId: 'eight-gps-project',
    authDomain: 'eight-gps-project.firebaseapp.com',
    storageBucket: 'eight-gps-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDummyAndroidApiKey123456789',
    appId: '1:123456789:android:1234567890abcdef',
    messagingSenderId: '123456789',
    projectId: 'eight-gps-project',
    storageBucket: 'eight-gps-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDummyiOSApiKey123456789',
    appId: '1:123456789:ios:1234567890abcdef',
    messagingSenderId: '123456789',
    projectId: 'eight-gps-project',
    storageBucket: 'eight-gps-project.appspot.com',
    iosBundleId: 'com.example.eightGps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDummymacOSApiKey123456789',
    appId: '1:123456789:macos:1234567890abcdef',
    messagingSenderId: '123456789',
    projectId: 'eight-gps-project',
    storageBucket: 'eight-gps-project.appspot.com',
    iosBundleId: 'com.example.eightGps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDummyWindowsApiKey123456789',
    appId: '1:123456789:windows:1234567890abcdef',
    messagingSenderId: '123456789',
    projectId: 'eight-gps-project',
    storageBucket: 'eight-gps-project.appspot.com',
  );
}
